-- MySQL Script generated by MySQL Workbench
-- Sat Jan 31 16:07:23 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Туризм
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Туризм
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Туризм` DEFAULT CHARACTER SET utf8 ;
USE `Туризм` ;

-- -----------------------------------------------------
-- Table `Туризм`.`Страны`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Туризм`.`Страны` (
  `idСтраны` INT NOT NULL AUTO_INCREMENT,
  `Страна` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idСтраны`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Туризм`.`Отели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Туризм`.`Отели` (
  `idОтели` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(45) NOT NULL,
  `idСтраны` INT NOT NULL,
  PRIMARY KEY (`idОтели`),
  CONSTRAINT `Страны`
    FOREIGN KEY (`idОтели`)
    REFERENCES `Туризм`.`Страны` (`idСтраны`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Туризм`.`Экскурссии`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Туризм`.`Экскурссии` (
  `idЭкскурссии` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(45) NOT NULL,
  `Цена` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idЭкскурссии`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Туризм`.`Клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Туризм`.`Клиенты` (
  `idКлиенты` INT NOT NULL AUTO_INCREMENT,
  `Имя` VARCHAR(45) NOT NULL,
  `Фамилия` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idКлиенты`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Туризм`.`Заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Туризм`.`Заказы` (
  `idЗаказы` INT NOT NULL AUTO_INCREMENT,
  `idКлиенты` INT NOT NULL,
  `idОтели` INT NOT NULL,
  `idЭкскурссии` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`idЗаказы`),
  INDEX `Клиенты_idx` (`idКлиенты` ASC) VISIBLE,
  INDEX `Отели_idx` (`idОтели` ASC) VISIBLE,
  INDEX `Экскурссии_idx` (`idЭкскурссии` ASC) VISIBLE,
  CONSTRAINT `Клиенты`
    FOREIGN KEY (`idКлиенты`)
    REFERENCES `Туризм`.`Клиенты` (`idКлиенты`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `Отели`
    FOREIGN KEY (`idОтели`)
    REFERENCES `Туризм`.`Отели` (`idОтели`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `Экскурссии`
    FOREIGN KEY (`idЭкскурссии`)
    REFERENCES `Туризм`.`Экскурссии` (`idЭкскурссии`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
